# Generated by Django 4.0.2 on 2024-03-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssistantProfile',
        ),
    ]
